services:
  - type: web
    name: homecare-dashboard
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: FIREBASE_API_KEY
        value: AIzaSyBWnaj_7qrK9pSBSI2sKSnFVLkyskhcZog
      - key: FIREBASE_AUTH_DOMAIN
        value: homecare-9f4d0.firebaseapp.com
      - key: FIREBASE_PROJECT_ID
        value: homecare-9f4d0
      - key: FIREBASE_STORAGE_BUCKET
        value: homecare-9f4d0.firebasestorage.app
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: 54787084616
      - key: FIREBASE_APP_ID
        value: 1:54787084616:web:2fe62181a935fefc08a37d 